name: flake8 Lint + Pytest

on:
  push:
    branches: [main, usuario]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 . --ignore=E1,E23,W503,F403,F401,E402,E501,E302
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  pytest:
    needs: flake8-lint
    runs-on: ubuntu-latest
    name: Pytest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests with pytest
        run: |
          export PYTHONPATH=${{ github.workspace }}/mlops_equipo1
          pytest mlops_equipo1/tests -v
